trigger:
  - main
jobs:
  - job: Job_1
    displayName: Copy files to app directory
    timeoutInMinutes: 2
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    - task: SSH@0
      displayName: Run shell commands on remote machine
      inputs:
        sshEndpoint: rosti
        commands: cd $(pull_directory);pwd;git pull
        readyTimeout: 10000
  - job: Job_2
    displayName: Restart app
    timeoutInMinutes: 1
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    - task: SSH@0
      displayName: Run shell commands on remote machine
      inputs:
        sshEndpoint: rosti
        commands: supervisorctl restart FAJN_Django
        readyTimeout: 10000
