trigger:
  - main
variables:
    AZP_IGNORE_SECRETS_SHORTER_THAN: 4
jobs:
  - job: Job_1
    displayName: Copy files to app directory
    timeoutInMinutes: 2
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    - task: SSH@0
      displayName: Run shell commands on remote machine
      inputs:
        sshEndpoint: rosti
        commands: source ~/.bashrc;azpull;git pull
        readyTimeout: 10000
  - job: Job_2
    dependsOn: Job_1
    displayName: Restart app
    timeoutInMinutes: 1
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    - task: SSH@0
      displayName: Run shell commands on remote machine
      inputs:
        sshEndpoint: rosti
        commands: supervisorctl restart FAJN_Django
        readyTimeout: 10000
