trigger:
- main

pool:
  name: Default

jobs:
- job: no_checkout_and_push_to_server
  steps:
  - script: |
     cd /srv/app
     git pull
    displayName: 'Git pull'

- job: restart_app
  steps:
  - script: supervisorctl restart FAJN_Django
    displayName: 'App restart'

checkout: none