trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest
  environment: 'venv'

steps:
- script: Git push
  displayName: 'Git push to server'

- script: |
   git checkout -b main
   git add -A
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin master
  workingDirectory: /srv/app
