trigger:
- main

pool:
  name: Default

jobs:
- job: no_checkout
  steps:
  - checkout: none

steps:
- script: |
   cd /srv/app
   git pull
   
  displayName: 'Command Line Script'

- script: |
   supervisorctl restart FAJN_Django
   
  displayName: 'Command Line Script'