version: '3'

services:
  mysql:
    container_name: fajn-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: local-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}

  web:
    container_name: fajn-ecommerce-TEST
    restart: always
    build: .
    working_dir: /srv/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - phpmyadmin
    volumes:
      - .:/srv/app
    user: 1000:1000
    command: python manage-local.py runserver 0.0.0.0:3000

volumes:
  db:
    driver: local
