# Generated by Django 4.1 on 2022-09-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_produkt_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='eanv',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='product_name',
        ),
        migrations.AddField(
            model_name='produkt',
            name='varianta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='varianta', to='listings.variants'),
        ),
    ]
