# Generated by Django 4.1 on 2022-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_variants_eanv_remove_variants_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
