# Generated by Django 4.1 on 2022-09-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_variants_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='price',
            field=models.IntegerField(),
        ),
    ]
