# Generated by Django 4.1 on 2022-11-10 21:30

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_produkt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_sub_category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.img_path_sub_sub_category),
        ),
        migrations.AlterField(
            model_name='sub_sub_category',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
