# Generated by Django 4.1 on 2022-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_sub_sub_category_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
