# Generated by Django 4.1 on 2023-01-12 23:27

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_produkt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='primary_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='primary_img',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.img_path),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_sub_category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='listings.sub_category'),
        ),
    ]
