# Generated by Django 4.1 on 2023-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_main_category_slug_sub_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sub_sub_category',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
